name: Checks

on:
  pull_request:
    branches: [master] # Core Branch name is 'master' and NOT 'main'


jobs:
  test-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yml
    secrets:
      # These are the Secrets that we defined in our GitHub repository.
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
